apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://localhost:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'Prometheus'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
