{
 "title": "API Response Times",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(validator_monitor_active, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(validator_monitor_validators_total{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP API: GET /validator/attestation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_validator_attestation_get_request_duration_seconds_sum{instance=\"$instance\",job=\"$job\"}[5m])\n/\nrate(http_server_validator_attestation_get_request_duration_seconds_count{instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP API: GET /validator/duties",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_validator_duties_get_request_duration_seconds_sum{instance=\"$instance\",job=\"$job\"}[5m])\n/\nrate(http_server_validator_duties_get_request_duration_seconds_count{instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP API: GET /validator/block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_validator_block_get_request_duration_seconds_sum{instance=\"$instance\",job=\"$job\"}[5m])\n/\nrate(http_server_validator_block_get_request_duration_seconds_count{instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  }
 ]
}