{
 "title": "Attestation Processing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Attestation Processing Metrics\n\nMetrics regarding `BeaconChain::process_attestation`, which processes `Attestation` from the network (but not in blocks).\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) crate.\n\n\n\n"
  },
  {
   "title": "Attestation Processing Total Time",
   "type": "graph",
   "description": "The `BeaconChain::fork_choice` function.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "\n### Verification Times\n\n\nTimes to verify the attestation contents and signature\n"
  },
  {
   "title": "Attestation Initial Validation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_initial_validation_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_initial_validation_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Shuffling Cache Wait Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_shuffling_cache_wait_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_shuffling_cache_wait_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Signature Verification Setup Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_signature_setup_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_signature_setup_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Signature Verification Time",
   "type": "graph",
   "description": "This is the time it takes to do just the BLS verification function (e.g., adding public keys, doing pairings, etc)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_signature_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_signature_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "content": "\n### State Processing Times\n\n\nTimes to read and process the state when the shuffling cache misses.\n"
  },
  {
   "title": "Attestation State Read Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_state_read_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_state_read_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation State Skip Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_state_skip_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_state_skip_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Attestation Committee Building Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_processing_committee_building_seconds_sum[5m])\n/\nrate(beacon_attestation_processing_committee_building_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "content": "\n### Cache Hits/Misses\n\n\nRates of success/failure when trying the shuffling cache.\n"
  },
  {
   "title": "Shuffling Cache Hits per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_shuffling_cache_hits_total[5m])"
    }
   ]
  },
  {
   "title": "Shuffling Cache Misses per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_shuffling_cache_misses_total[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "content": "\n### Requests and Successes\n\n\nTracks the number of attestation processing requests and successes\n"
  },
  {
   "title": "Attestations Processed per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_attestation_processing_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Attestations Successfully Imported per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_attestation_processing_successes_total[1m])"
    }
   ]
  },
  {
   "title": "Attestations Rejected Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_attestation_processing_requests_total - beacon_attestation_processing_successes_total"
    }
   ]
  }
 ]
}