{
 "title": "Attestation Production",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "\n# Attestation Production Metrics\n\nMetrics regarding `BeaconChain::produce_attestation_data`, used by a validator to produce an `Attestation`.\n\nCollected from the [`beacon_chain`](https://github.com/sigp/lighthouse/tree/master/beacon_node/beacon_chain) crate.\n\n\n\n"
  },
  {
   "title": "Attestation Production Total Time",
   "type": "graph",
   "description": "The `BeaconChain::fork_choice` function.",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestation_production_seconds_sum[5m])\n/\nrate(beacon_attestation_production_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 6 },
   "content": "\n### Requests and Successes\n\n\nTracks the number of attestation production requests and successes\n"
  },
  {
   "title": "Attestation Production Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_attestation_production_requests_total"
    }
   ]
  },
  {
   "title": "Attestations Successfully Produced",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Attestations" }
   ],
   "targets": [
    {
     "expr": "beacon_attestation_production_successes_total"
    }
   ]
  }
 ]
}