{
 "title": "Beacon Chain & Store",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki", "label": "Loki", "query": "loki" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(node_uname_info, network)"
    }
   },
   { "name": "node", "label": "Instance Filter (regex)", "query": ".*" },
   { "name": "quantile", "label": "Histogram Quantile", "query": "0.99" }
  ]
 },
 "panels": [
  {
   "title": "Head State Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "beacon_head_state_slot",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "beacon_head_slot{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_slot % 32",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "beacon_head_slot{network=~\"${network}\", instance=~\"${node}\"} % 32",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_current_justified_epoch",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "beacon_current_justified_epoch{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_previous_justified_epoch",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "targets": [
      {
       "expr": "beacon_previous_justified_epoch{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_finalized_epoch",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "beacon_finalized_epoch{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_slot",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "beacon_head_state_latest_block_slot{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_current_active_validators",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "beacon_current_active_validators{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_validator_balances_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "expr": "beacon_head_state_validator_balances_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_slashed_validators_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "beacon_head_state_slashed_validators_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_total_validators_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "beacon_head_state_total_validators_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_eth1_deposit_index",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "beacon_head_state_eth1_deposit_index{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_processed_deposits_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "beacon_processed_deposits_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_head_state_withdrawn_validators_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "beacon_head_state_withdrawn_validators_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "beacon_block_processing_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_successes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_snapshot_cache_misses",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_snapshot_cache_misses{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_snapshot_cache_clones",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
     "targets": [
      {
       "expr": "rate(beacon_block_processing_snapshot_cache_clones{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_snapshot_cache_size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "beacon_block_processing_snapshot_cache_size{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_early_attester_cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "targets": [
      {
       "expr": "rate(beacon_early_attester_cache_hits{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_block_root_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_block_root_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "execution_layer_request_times: new_payload",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(execution_layer_request_times_bucket{network=~\"${network}\", instance=~\"${node}\", method=\"new_payload\"}[5m]))",
       "legendFormat": "{{instance}} - {{method}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_committee_building_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_committee_building_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_signature_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_signature_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_db_read_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_db_read_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_db_write_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_db_write_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_state_root_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_state_root_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_state_root_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "beacon_block_processing_state_root_seconds_sum{network=~\"${network}\", instance=~\"${node}\"} / beacon_block_processing_state_root_seconds_count{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_core_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_core_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_fork_choice_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_fork_choice_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_attestation_observation_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_attestation_observation_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_catch_up_state_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_catch_up_state_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_block_processing_signature_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_block_processing_signature_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "store_beacon_block_cache_hit_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(store_beacon_block_cache_hit_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_block_get_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "rate(store_beacon_block_get_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_read_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "rate(store_beacon_state_read_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_read_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(store_beacon_state_read_bytes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_write_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(store_beacon_state_write_bytes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_hot_get_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "rate(store_beacon_state_hot_get_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_get_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(store_beacon_state_get_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_write_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "rate(store_beacon_state_write_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_read_overhead_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(store_beacon_state_read_overhead_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_write_overhead_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(store_beacon_state_write_overhead_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_beacon_state_read_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(store_beacon_state_read_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_read_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(store_disk_db_read_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_read_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(store_disk_db_read_bytes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_read_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "rate(store_disk_db_read_count_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_read_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(store_disk_db_read_bytes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "store_disk_db_size{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_write_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(store_disk_db_write_bytes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_exists_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "expr": "rate(store_disk_db_exists_count_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_freezer_db_size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "store_freezer_db_size{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "store_disk_db_write_count_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "expr": "rate(store_disk_db_write_count_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Block Delays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "beacon_block_delay_total",
   "type": "timeseries",
   "description": "Duration between the start of the block's slot and the time when it was set as head.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_total{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_observed_slot_start",
   "type": "timeseries",
   "description": "Duration between the start of the block's slot and the time the block was observed.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_observed_slot_start{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_blob_delay_all_observed_slot_start",
   "type": "timeseries",
   "description": "Duration between the start of the block's slot and the time the block was observed.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_blob_delay_all_observed_slot_start{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_consensus_verification_time",
   "type": "timeseries",
   "description": "The time taken to verify the block within Lighthouse",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_consensus_verification_time{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_execution_time",
   "type": "timeseries",
   "description": "The duration in verifying the block with the execution layer.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_execution_time{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_available_slot_start",
   "type": "timeseries",
   "description": "Duration between the time that block became available and the start of the slot.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_available_slot_start{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_attestable_slot_start",
   "type": "timeseries",
   "description": "Duration between the time that block became attestable and the start of the slot.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_attestable_slot_start{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_imported_time",
   "type": "timeseries",
   "description": "Duration between the time the block became available and the time when it was imported.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_imported_time{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_head_imported_time",
   "type": "timeseries",
   "description": "Duration between the time that block was imported and the time when it was set as head.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_head_imported_time{network=~\"${network}\", instance=~\"${node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_delay_head_slot_start_exceeded_total",
   "type": "timeseries",
   "description": "A counter that is triggered when the duration between the start of the block's slot and the current time will result in failed attestations.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_block_delay_head_slot_start_exceeded_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Block Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "beacon_block_production_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_successes_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_fork_choice_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_fork_choice_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_state_load_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_state_load_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_slot_process_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_slot_process_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_unaggregated_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_unaggregated_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_attestation_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_attestation_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_process_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_process_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_state_root_seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_state_root_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_get_proposer_head_times",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_get_proposer_head_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Fork Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "beacon_fork_choice_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_errors_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_changed_head_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_changed_head_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_reorgs_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "rate(beacon_reorgs_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_balances_cache_hits_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(beacon_balances_cache_hits_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_balances_cache_misses_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "expr": "rate(beacon_balances_cache_misses_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_override_fcu_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_override_fcu_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_process_block_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_process_block_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_process_attestation_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_process_attestation_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_block_production_get_proposer_head_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_block_production_get_proposer_head_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_after_new_head_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_after_new_head_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_after_finalization_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_after_finalization_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_persist_head_bucket_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_persist_head_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_fork_choice_set_head_lag_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_fork_choice_set_head_lag_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_update_head_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_update_head_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Attestation Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "beacon_shuffling_cache_hits_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(beacon_shuffling_cache_hits_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_shuffling_cache_misses_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "rate(beacon_shuffling_cache_misses_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_unaggregated_attestation_processing_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "rate(beacon_unaggregated_attestation_processing_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_unaggregated_attestation_processing_successes_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "rate(beacon_unaggregated_attestation_processing_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_unaggregated_attestation_gossip_verification_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_unaggregated_attestation_gossip_verification_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_aggregated_attestation_processing_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(beacon_aggregated_attestation_processing_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_aggregated_attestation_processing_successes_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "targets": [
    {
     "expr": "rate(beacon_aggregated_attestation_processing_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_aggregated_attestation_gossip_verification_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_aggregated_attestation_gossip_verification_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_apply_to_agg_pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_apply_to_agg_pool_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_agg_pool_prune",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_agg_pool_prune_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_agg_pool_insert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_agg_pool_insert_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_agg_pool_core_insert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_agg_pool_core_insert_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_agg_pool_aggregation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_agg_pool_aggregation_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_agg_pool_create_map",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_agg_pool_create_map_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_apply_to_op_pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_apply_to_op_pool_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_shuffling_cache_wait_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_shuffling_cache_wait_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_committee_building_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_committee_building_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_state_read_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_state_read_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_state_skip_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_state_skip_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_signature_setup_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_signature_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_signature_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_batch_agg_signature_setup_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_batch_agg_signature_setup_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_batch_agg_signature_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_batch_agg_signature_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_batch_unagg_signature_setup_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_batch_unagg_signature_setup_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "beacon_attestation_processing_batch_unagg_signature_times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_processing_batch_unagg_signature_times_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Attestation Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "beacon_attestation_production_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(beacon_attestation_production_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "attestation_production_head_scrape_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(attestation_production_head_scrape_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "attestation_production_cache_interaction_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(attestation_production_cache_interaction_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "attestation_production_cache_prime_seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, rate(attestation_production_cache_prime_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "beacon_op_pool_attestations_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "beacon_op_pool_attestations_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_attestation_data_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "targets": [
      {
       "expr": "beacon_op_pool_attestation_data_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_max_aggregates_per_data",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "beacon_op_pool_max_aggregates_per_data{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_attester_slashings_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "targets": [
      {
       "expr": "beacon_op_pool_attester_slashings_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_proposer_slashings_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "beacon_op_pool_attester_slashings_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_voluntary_exits_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "beacon_op_pool_voluntary_exits_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_op_pool_sync_contributions_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "beacon_op_pool_sync_contributions_total{network=~\"${network}\", instance=~\"${node}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Committee Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true,
   "panels": [
    {
     "title": "beacon_sync_committee_message_processing_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(beacon_sync_committee_message_processing_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_committee_message_processing_successes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "rate(beacon_sync_committee_message_processing_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_committee_message_gossip_verification_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_committee_message_gossip_verification_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(beacon_sync_contribution_processing_requests_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_successes_total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "rate(beacon_sync_contribution_processing_successes_total{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_gossip_verification_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_gossip_verification_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_apply_to_agg_pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_apply_to_agg_pool_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_agg_pool_prune",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_agg_pool_prune_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_agg_pool_insert",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_agg_pool_insert_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_agg_pool_core_insert",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_agg_pool_core_insert_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_agg_pool_aggregation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_agg_pool_aggregation_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_agg_pool_create_map",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_agg_pool_create_map_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_apply_to_op_pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_apply_to_op_pool_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_signature_setup_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_signature_setup_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_signature_setup_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_sync_contribution_processing_signature_setup_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_sync_contribution_processing_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backfill",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "panels": [
    {
     "title": "beacon_backfill_signature_setup_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_backfill_signature_setup_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_backfill_signature_verify_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_backfill_signature_verify_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "beacon_backfill_signature_total_seconds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, rate(beacon_backfill_signature_total_seconds_bucket{network=~\"${network}\", instance=~\"${node}\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}