{
 "title": "Block delays",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Long-term",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block observation delay (proposer & network dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_observed_slot_start_delay_time_sum[2h])/rate(beacon_block_observed_slot_start_delay_time_count[2h])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[2h])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[2h])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[2h])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Block import delay (CPU & I/O dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_imported_observed_delay_time_sum[2h])/rate(beacon_block_imported_observed_delay_time_count[2h])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_imported_observed_delay_time_bucket[2h])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_imported_observed_delay_time_bucket[2h])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_imported_observed_delay_time_bucket[2h])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Set as head (CPU, I/O and re-org dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_head_imported_delay_time_sum[2h])/rate(beacon_block_head_imported_delay_time_count[2h])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_head_imported_delay_time_bucket[2h])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_head_imported_delay_time_bucket[2h])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_head_imported_delay_time_bucket[2h])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Short-term",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block observation delay (proposer & network dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_observed_slot_start_delay_time_sum[24s])/rate(beacon_block_observed_slot_start_delay_time_count[24s])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_observed_slot_start_delay_time_bucket[5m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Block import delay (CPU & I/O dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_imported_observed_delay_time_sum[24s])/rate(beacon_block_imported_observed_delay_time_count[24s])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_imported_observed_delay_time_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_imported_observed_delay_time_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_imported_observed_delay_time_bucket[5m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Set as head (CPU, I/O and re-org dependent)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_head_imported_delay_time_sum[24s])/rate(beacon_block_head_imported_delay_time_count[24s])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(beacon_block_head_imported_delay_time_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(beacon_block_head_imported_delay_time_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(beacon_block_head_imported_delay_time_bucket[5m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  }
 ]
}