{
 "title": "Lighthouse Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Health\n \n           " } },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peer_connected_peers_total",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "NAT",
   "type": "stat",
   "description": "Is the UDP port forwarded",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "expr": "nat_open" }
   ]
  },
  {
   "title": "Blocks Per Slot",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_blocks_rx_total[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "piechart",
   "description": "Peers via client implementations",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers_per_client", "legendFormat": "{{Client}}" }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "description": "Peers that have dialed us",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_inbound_peers", "legendFormat": "Inbound" },
    { "expr": "network_outbound_peers", "legendFormat": "Outbound" }
   ]
  },
  {
   "title": "Total Libp2p Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(libp2p_inbound_bytes[1m])", "legendFormat": "bytes/s" }
   ]
  },
  {
   "title": "Libp2p Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_outbound_bytes[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Average Peer Score Per Client",
   "type": "piechart",
   "description": "Average Peer score per client shifted by 100",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peer_score_per_client+100", "legendFormat": "{{client}}" }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "Peers sync status",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_peers_per_status", "legendFormat": "{{sync_status}}" }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth[$__rate_interval]) + rate(discovery_sent_bytes[$__rate_interval]) + rate(discovery_recv_bytes[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Inbound Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_recv_bytes[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_sent_bytes[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "# Discovery Metrics\n \n           "
   }
  },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "discovery_requests", "legendFormat": "Requests/s" }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "discovery_sessions", "legendFormat": "active sessions" }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "discovery_queue_size", "legendFormat": "Queued Discoveries" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 }, "options": { "content": "# RPC Metrics\n \n           " } },
  {
   "title": "Connected Peer Score Distribution",
   "type": "timeseries",
   "description": "Distribution of connected peer's score by quartile",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "peer_score_distribution", "legendFormat": "{{position}}" }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(libp2p_rpc_errors_per_client{}[$__rate_interval]))",
     "legendFormat": "Errors Per Second"
    }
   ]
  },
  {
   "title": "RPC Errors (Non timeout)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{rpc_error=~\"incomplete_stream|invalid_request|io_error\"}",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "RPC Timeouts Per Client",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_rpc_errors_per_client{rpc_error=~\"negotiation_timeout|stream_timeout\"}",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "10m Average RPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "rate(libp2p_rpc_requests_total[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "# Gossipsub Metrics\n \n           "
   }
  },
  {
   "title": "Mesh Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "gossipsub_mesh_peer_counts{hash=~\"/eth2/afcaaba0/beacon_aggregate_and_proof/ssz_snappy|/eth2/afcaaba0/beacon_block/ssz_snappy\"}",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Blocks Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=\"/eth2/afcaaba0/beacon_block/ssz_snappy\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Aggregated Attestations Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=\"/eth2/afcaaba0/beacon_aggregate_and_proof/ssz_snappy\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Invalid Messages Per Topic Per Slot",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_invalid_message_topic[$__rate_interval])*12",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "gauge",
   "description": "Cache Misses over a 10m window",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_memcache_misses_total[10m])"
    }
   ]
  },
  {
   "title": "Average Peer Score per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_topic",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "10m Average of Block Delay from Start of Slot",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(beacon_block_gossip_slot_start_delay_time_bucket[10m])*12",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IWANT Requests Per Slot",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_iwant_requests[$__rate_interval])*12",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Ignored Messages Per Slot",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(gossipsub_mesh_metrics_by_topic{metric=\"MessagesIgnored\",topic=~\"attester_slashing|beacon_aggregate_and_proof|beacon_block|proposer_slashing|signed_contribution_and_proof|voluntary_exit\"}[1m]))*12",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "30s Block Delay Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(beacon_block_gossip_slot_start_delay_time_sum[30s])/rate(beacon_block_gossip_slot_start_delay_time_count[30s])",
     "legendFormat": "Block Delay"
    }
   ]
  },
  {
   "title": "Duplicates Filtered Per Slot",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(gossipsub_mesh_metrics_by_topic{metric=\"MessagesDuplicates\",topic=~\"attester_slashing|beacon_aggregate_and_proof|beacon_block|proposer_slashing|signed_contribution_and_proof|voluntary_exit\"}[1m]))*12",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub Ignored Messages Per Client",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_unaccepted_messages_per_client",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "BeaconBlock Mesh Peers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_mesh_peers_per_client", "legendFormat": "{{Client}}" }
   ]
  },
  {
   "title": "BeaconAggregateAndProof Mesh Peers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_aggregate_and_proof_mesh_peers_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Mean scores per client",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_mean_scores_per_client",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Broken Promises Per Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(gossipsub_broken_promises[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Attestation Errors Per Slot",
   "type": "timeseries",
   "description": "Gossipsub Attestation Errors By Type",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(gossipsub_attestation_errors_per_type[$__rate_interval])*12",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Subscribed Peers Per Subnet",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_peers_per_attestation_subnet_topic_count",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Subscribed Peers Per Sync Committee",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_peers_per_sync_subnet_topic_count",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Average Peer Score Per Subnet",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 4, "x": 8, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_attestation_subnet_topic",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Average Peer Score Per Sync Committee",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 12, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_sync_subnet_topic",
     "legendFormat": "{{subnet}}"
    }
   ]
  }
 ]
}