{
 "title": "Malloc Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Snapshot Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_block_processing_snapshot_cache_size"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_arena + mallinfo_hblkhd"
    }
   ]
  },
  {
   "title": "Non-mmap memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_arena" }
   ]
  },
  {
   "title": "Mem-mapped bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_hblkhd" }
   ]
  },
  {
   "title": "Mem-mapped blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mallinfo_hblks", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Free blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mallinfo_ordblks", "legendFormat": "{{__name__}} {{instance}}" },
    { "expr": "mallinfo_smblks", "legendFormat": "{{__name__}} {{instance}}" }
   ]
  },
  {
   "title": "In-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_uordblks" }
   ]
  },
  {
   "title": "Fastbin free memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_fsmblks" }
   ]
  },
  {
   "title": "Free block memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_fordblks" }
   ]
  },
  {
   "title": "Releasable heap top memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mallinfo_keepcost" }
   ]
  }
 ]
}