{
 "title": "Lighthouse PeerDAS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  {
   "title": "Beacon Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc_custody_column_queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(beacon_processor_rpc_custody_column_queue_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "rpc_verify_data_column_queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(beacon_processor_rpc_verify_data_column_queue_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Column Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "column_processing_requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(beacon_blobs_column_sidecar_processing_requests_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "column_processing_successes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(beacon_blobs_column_sidecar_processing_successes_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "column_processing_failures",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(beacon_blobs_column_sidecar_processing_requests_total{instance=~\"$Instance\"}[$__rate_interval])) - sum by(instance) (rate(beacon_blobs_column_sidecar_processing_successes_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "KZG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "column_sidecar_computation_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(data_column_sidecar_computation_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "column_reconstruction_time_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(data_availability_reconstruction_time_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "reconstructed_columns_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(data_availability_reconstructed_columns_total{instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kzg_verification_data_column_single_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(kzg_verification_data_column_single_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "kzg_verification_data_column_batch_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(kzg_verification_data_column_batch_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "column_sidecar_inclusion_proof_verification_seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(data_column_sidecar_inclusion_proof_verification_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "libp2p_peers{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "piechart",
     "description": "Peers via client implementations",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_peers_per_client{instance=~\"$Instance\"}",
       "legendFormat": "{{Client}}"
      }
     ]
    },
    {
     "title": "Total Libp2p Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(libp2p_bandwidth_bytes_total{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Libp2p Inbound Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(libp2p_bandwidth_bytes_total{instance=~\"$Instance\",direction=\"Inbound\"}[1m]))",
       "legendFormat": "bytes/s"
      }
     ]
    },
    {
     "title": "Libp2p Outbound Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(libp2p_bandwidth_bytes_total{instance=~\"$Instance\",direction=\"Outbound\"}[1m]))",
       "legendFormat": "bytes/s"
      }
     ]
    },
    {
     "title": "Average Peer Score Per Client",
     "type": "piechart",
     "description": "Average Peer score per client shifted by 100",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "peer_score_per_client{instance=~\"$Instance\"}+100",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Total Discovery Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(discovery_bytes{instance=~\"$Instance\", }[$__rate_interval]))",
       "legendFormat": "{{instance}} bytes/s"
      }
     ]
    },
    {
     "title": "Discovery Inbound Bandwith",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(discovery_bytes{instance=~\"$Instance\",direction=\"inbound\"}[$__rate_interval]))",
       "legendFormat": "bytes/s"
      }
     ]
    },
    {
     "title": "Discovery Outbound Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(discovery_bytes{instance=~\"$Instance\",direction=\"outbound\"}[$__rate_interval]))",
       "legendFormat": "bytes/s"
      }
     ]
    }
   ]
  }
 ]
}