{
 "title": "Slasher",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(validator_monitor_active, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(validator_monitor_validators_total{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Batch processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(slasher_process_batch_time_sum{instance=\"$instance\",job=\"$job\"}[30s])\n/\nrate(slasher_process_batch_time_count{instance=\"$instance\",job=\"$job\"}[30s])"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "slasher_database_size{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Valid attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_attestations_valid{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Deferred attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_attestations_deferred{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Dropped attestations per batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_attestations_dropped{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Blocks per batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_num_blocks_processed{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Chunk compression ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slasher_compression_ratio{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Chunks updated per batch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(slasher_num_chunks_updated{instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  }
 ]
}