{
 "title": "Sync Traces",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SyncingChain",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "syncing_chain" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{name=\"syncing_chain\"}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Range RPC Requests",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "syncing_chain" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{name=\"outgoing_range_request\"}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Process Chain Segment",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "syncing_chain" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{name=\"process_chain_segment\"}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Pending Components",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "syncing_chain" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{name=\"pending_components\"}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Gossip block / blobs",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "process_gossip_data_column",
        "process_gossip_block"
       ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{(name=\"process_gossip_data_column\" || name=\"process_gossip_block\")}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Lookup RPC Requests",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "d83d2c03", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "outgoing_custody_request",
        "process_rpc_block",
        "process_rpc_custody_columns"
       ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{(name=\"outgoing_custody_request\" || name=\"process_rpc_block\" || name=\"process_rpc_custody_columns\")}",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Outgoing DataColumnByRoot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request median duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\nhistogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"batch_columns_req\"}[$__rate_interval])) by (le, client)),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "{{attributes_client}}"
      }
     ]
    },
    {
     "title": "Request count by client",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nlabel_replace(\nsum by (client) (\n  traces_spanmetrics_calls_total{span_name=\"batch_columns_req\"}\n),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "{{attributes_client}}"
      }
     ]
    },
    {
     "title": "DataColumnsByRoot with missing columns from peers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\nsum by (client) (traces_spanmetrics_calls_total{\n    span_name=\"batch_columns_req\", missing_column_indexes!=\"\"\n  }),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "{{attributes_client}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing DataColumnByRange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request median duration by result",
     "type": "stat",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\n\nhistogram_quantile(0.50,\n  sum by (le, result) (\n    rate(traces_spanmetrics_latency_bucket{span_name=\"outgoing_columns_by_range\"}[5m])\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Completed request median duration by client",
     "type": "stat",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\n\nhistogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{span_name=\"outgoing_columns_by_range\",result=~\"Completed.*\"}[$__rate_interval])) by (le, client)),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DataColumnByRange request results by client",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(\nsum by (result, client) (\n  traces_spanmetrics_calls_total{span_name=\"outgoing_columns_by_range\",result=~\".+\"}),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "{{client}}: {{result}}"
      }
     ]
    },
    {
     "title": "Completed requests by client",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nlabel_replace(\nsum by (client) (\n  traces_spanmetrics_calls_total{span_name=\"outgoing_columns_by_range\", result=~\"Completed.*\"}\n),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total error count by client",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "\nlabel_replace(\nsum by (client) (\n  traces_spanmetrics_calls_total{span_name=\"outgoing_columns_by_range\", result=\"RPCError\"}\n),\n  \"client\", \"Grandine\", \"client\", \"^Unknown$\"\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming RPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer RPC requests by client",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (client, span_name) (traces_spanmetrics_calls_total{span_name=~\"handle.*\"})",
       "legendFormat": "{{client}}, {{span_name}}"
      }
     ]
    },
    {
     "title": "DataColumnByRoot req with non custody indices",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 61 },
     "targets": [
      {
       "expr": "sum by (client) (traces_spanmetrics_calls_total{span_name=\"handle_data_columns_by_root_request\", non_custody_indices!=\"[]\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DataColumnByRoot req with non custody indices",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 61 },
     "targets": [
      {
       "expr": "sum by (client) (traces_spanmetrics_calls_total{span_name=\"handle_data_columns_by_range_request\", non_custody_indices!=\"[]\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}