{
 "title": "Validator Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Lighthouse Validator Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "Metrics collected from a Lighthouse Beacon Node.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validator Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Gwei" }
   ],
   "targets": [
    { "expr": "validator_monitor_balance_gwei" }
   ]
  },
  {
   "title": "Active Validators",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_active)" }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_slashed)" }
   ]
  },
  {
   "title": "Monitored Validators Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Validators" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_validators_total"
    }
   ]
  },
  {
   "title": "Exited Validators",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(validator_monitor_exited)" }
   ]
  },
  {
   "title": "Withdrawable Validators",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_withdrawable)"
    }
   ]
  },
  { "title": "Missed blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "Displays the amount of missed blocks per validator in real-time."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Missed Blocks per Validator",
   "type": "piechart",
   "description": "Displays the missed blocks per validator starting from the first validated epoch",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_monitor_missed_blocks_total{}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Missed Blocks per Validator at Non-finalized Epochs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_monitor_missed_non_finalized_blocks_total{} > 0",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Missed Blocks per Validator Seen at Non-finalized Epochs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "validator_monitor_missed_non_finalized_blocks_total{}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Summary of Events in the Previous Epoch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "Contains the summary of validator events in the previous epoch. These figures can be used to monitor the performance and online-ness of specific validators.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prev Epoch Attestation included in Block",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Block Inclusions" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_inclusions"
    }
   ]
  },
  {
   "title": "Prev Epoch Unagg Attestations Seen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestations_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Aggregate Attestations Seen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "SignedAggregateAndProof" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_aggregates_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Blocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_beacon_blocks_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Attestation included in Aggregate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "Aggregate Inclusions" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_aggregate_inclusions"
    }
   ]
  },
  {
   "title": "Prev Epoch Voluntary Exits Seen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "VoluntaryExit" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_exits_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Proposer Slashing Seen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "ProposerSlashing" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_proposer_slashings_total"
    }
   ]
  },
  {
   "title": "Prev Epoch Attester Slashing Seen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "AttesterSlashing" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attester_slashings_total"
    }
   ]
  },
  {
   "title": "Minimum Message Delays in the Previous Epoch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "These are the delays between when a message was due and when we recieved it. The values displayed here are the minimum delays per validator.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prev Epoch Min Attestation Inclusion Delay (Slots)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_min_inclusion_distance"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Unagg. Attestation Delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_attestations_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_attestations_min_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Block Delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Prev Epoch Min Aggregate Attestation Delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_aggregates_min_delay_seconds_sum[30s])\n/\nrate(validator_monitor_prev_epoch_aggregates_min_delay_second_count[30s])"
    }
   ]
  },
  {
   "title": "Attestation Inclusion in a Block per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "none", "label": "Block Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_block_total[1m])"
    }
   ]
  },
  { "title": "Real-Time Validator Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "Displays events happening per validator in real-time.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Attestation inclusion in Block per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "Block Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_block_total[1m])"
    }
   ]
  },
  {
   "title": "Unaggregated Attestations Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_unaggregated_attestation_total[1m])"
    }
   ]
  },
  {
   "title": "Aggregated Attestations Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "none", "label": "SignedAggregateAndProof" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_aggregated_attestation_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon Blocks Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 66 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_beacon_block_total[1m])"
    }
   ]
  },
  {
   "title": "Attestation inclusion in Aggregate per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "none", "label": "Aggregate Inclusions" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_in_aggregate_total[1m])"
    }
   ]
  },
  {
   "title": "Voluntary Exits Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "VoluntaryExit" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_exit_total[1m])"
    }
   ]
  },
  {
   "title": "Proposer Slashing Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "ProposerSlashing" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_proposer_slashing_total[1m])"
    }
   ]
  },
  {
   "title": "Attester Slashing Seen per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "AttesterSlashing" }
   ],
   "targets": [
    {
     "expr": "increase(validator_monitor_attester_slashing_total[1m])"
    }
   ]
  },
  {
   "title": "Real-Time Validator Message Delays",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "Displays message delays per validator in real-time.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Attestation Inclusion Delay (Slots)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_attestation_in_block_delay_slots"
    }
   ]
  },
  {
   "title": "Unaggregated Attestation Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 80 },
   "targets": [
    {
     "expr": "rate(validator_monitor_unaggregated_attestation_delay_seconds_sum[30s])\n/\nrate(validator_monitor_unaggregated_attestation_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Beacon Block Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 80 },
   "targets": [
    {
     "expr": "rate(validator_monitor_beacon_block_delay_seconds_sum[30s])\n/\nrate(validator_monitor_beacon_block_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Aggregated Attestation Delay Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 85 },
   "targets": [
    {
     "expr": "rate(validator_monitor_aggregated_attestation_delay_seconds_sum[30s])\n/\nrate(validator_monitor_aggregated_attestation_delay_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Inclusion in Attestation Delay",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "expr": "rate(validator_monitor_attestation_in_aggregate_delay_seconds_sum[30s])\n/\nrate(validator_monitor_attestation_in_aggregate_delay_seconds_count[30s])"
    }
   ]
  }
 ]
}